### ISSUE TITLE
Inter-children communication

### ISSUE THREAD

**Issue by vallettea** [untu/comedy#2]
Since the root actor creates all the children sequentially, I don't see how different kind of children can exchange messages without passing by root.

For example, I need my `Player` actor to send data to `Croupier`.
The two choices I see are:

- create the two actors simultaneously and add a setter:
```
class Player {
    constructor() {
        this.currentPile = []
        this.master = null
    }

    start(pile) {
        this.currentPile = pile;
        this.currentPile.forEach((x) => this.master.send('add', x))
    }

    setMaster(master) {
        this.master = master
    }
}

class Croupier {
    constructor() {
        this.pile = []
    }

    add(value) {
        this.pile.push(value);
    }

    print(to) {
        console.log(this.pile);
    }
}

var actorSystem = actors();

actorSystem
  .rootActor() // Get a root actor reference.
  .then(function(rootActor) {
    Promise.all([rootActor.createChild(Player, {mode: 'forked', clusterSize: 3}), rootActor.createChild(Croupier)])
    .then(children => {
        var player = children[0];
        var croupier = children[1];
        player.send('setMaster', croupier);
        player.send('start', [1,2,3]);
        setInterval(() => croupier.send('print'), 1000)
      })
  })
```

- create actor one after the other and set the master in the constructor of the first actor.

Anyhow, when running the previous code, there is an error (again only when forked):

```
Unhandled rejection TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ChildProcess.target._send (internal/child_process.js:626:23)
    at ChildProcess.target.send (internal/child_process.js:538:19)
    at P (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/forked-actor.js:322:16)
    at Promise._execute (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/promise.js:77:14)
    at ForkedActorParent._send0 (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/forked-actor.js:298:12)
    at ForkedActorParent._sendActorMessage (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/forked-actor.js:263:17)
    at ForkedActorParent.send0 (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/forked-actor.js:183:17)
    at ForkedActorParent.send (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/actor.js:161:19)
    at ForkedActorStub.send (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/forked-actor-stub.js:70:23)
    at currentChildPromise.then.child (/Users/vallettea/Desktop/actors/node_modules/comedy/lib/standard/round-robin-balancer-actor.js:119:64)
    at tryCatcher (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/vallettea/Desktop/actors/node_modules/bluebird/js/release/promise.js:567:18)
```

What I am doing wrong ?

**Comment by vallettea** [comment]
Reading the [previous comment](https://github.com/untu/comedy/issues/1#issuecomment-271248661), I guess I should use `forwardToChild` and make all messages go through root. 
Do you confirm ?

Sorry to disturb you, but I comme from Akka actors in scala and things are a bit different there as there is no root actor.

**Comment by weekens** [comment]
@vallettea , great that you've used Akka before!

In Akka, there is a feature called "actor references". It's essentially a way to set up communication between any two actors of your choice.

In Comedy, "actor references" are not yet implemented and are still to come (just like "remote actors"). For now you only have an option to communicate through parent actor.

I will tag this issue as a feature request. I don't think this will take much time for forked actors.

**Comment by vallettea** [comment]
👍 +1

**Comment by weekens** [comment]
Implemented references for forked and remote actors.
