### ISSUE TITLE
"Error: externalFunction is not defined" in forked nodes

### ISSUE THREAD

**Issue by aarcangeli** [untu/comedy#38]
I'm getting an error when I try to reference external symbols in forked agents.
Am I doing something wrong?

### My code:
```js
const actors = require('comedy');

function externalFunction() {
    console.log("CIAO");
}

/**
 * Actor definition class.
 */
let MyActor = {
    sayHello: function () {
        externalFunction();
    }
};

async function bootstrap() {
    let actorSystem = actors();
    try {
        let root = await actorSystem.rootActor();
        console.log("== Creating in memory actor ==");
        await (await root.createChild(MyActor, {mode: 'in-memory'})).sendAndReceive(`sayHello`); // ok
        console.log("== Creating forked actor ==");
        await (await root.createChild(MyActor, {mode: 'forked'})).sendAndReceive(`sayHello`); // not ok
    } catch (e) {
        console.log("error: ", e);
        await actorSystem.destroy();
    }
}

bootstrap();
```

### My expected result:
```
== Creating in memory actor ==
CIAO
== Creating forked actor ==
CIAO
```

### My actual result:
```
Tue Jun 11 2019 09:42:40 GMT+0200 (GMT+02:00) - info: Didn't find (or couldn't load) default configuration file C:\comedy-sandbox/actors.json.
Tue Jun 11 2019 09:42:40 GMT+0200 (GMT+02:00) - info: Resulting actor configuration: {}
== Creating in memory actor ==
CIAO
== Creating forked actor ==
error:  Error: externalFunction is not defined
    at ChildProcess.bus.on (C:\comedy-sandbox\node_modules\comedy\lib\forked-actor.js:224:32)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Tue Jun 11 2019 09:42:41 GMT+0200 (GMT+02:00) - info: Killing forked system process.
Tue Jun 11 2019 09:42:41 GMT+0200 (GMT+02:00) - info: ForkedActorParent(5cff5b70806f34235cfa76d1, Object): Actor process exited, actor ForkedActorParent(5cff5b70806f34235cfa76d1, Object)
```

### My Environment:
**OS**: Windows 10
**node --version**: v10.15.3
**npm --version**: 6.9.0
**npm info comedy version**: 2.1.0

**Comment by aarcangeli** [comment]
But also: modifying the code as follow it give me another error:

```js
let MyActor = {
    sayHello() {
        externalFunction();
    }
};
```

```
== Creating in memory actor ==
CIAO
== Creating forked actor ==
error:  Error: Compilation error: SyntaxError: Unexpected token {
    at ChildProcess.workerProcess.once.msg (C:\comedy-sandbox\node_modules\comedy\lib\forked-actor-parent.js:150:33)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by weekens** [comment]
You're getting an error, because the forked actor is started in a separate process, which is not aware of `externalFunction` function. Please have a closer look about [this note](https://github.com/untu/comedy#important-note-about-code-transfer) in the docs.

To successfully call your function, you need to move your actor to a separate module (maked it a module actor), export `externalFunction` function and import in into your actor module. Also, when launching an actor with `createChild`, you'll specify the module path to your actor instead of a class reference. This way, the `externalFunction` will be available even in a separate process and the example will work.

**Comment by aarcangeli** [comment]
Thank you for the reply.
I haven't read the documentation enough.
